name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pylint
        if [ -f req.txt ]; then pip install -r req.txt; fi
    - name: Lint with pylint
      run: |
        pylint app.py
    - name: Test with pytest
      run: |
        pytest test.py
